spring:
  application:
    name: orders-service
  
  ## RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:dwfs}
    password: ${RABBITMQ_PASSWORD:rabbitmq}
    virtual-host: ${RABBITMQ_VHOST:/}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:32792/order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: relatosdepapel-orders-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Data Seeding Configuration
app:
  seed:
    enabled: true
    orders-count: 15 # Número de órdenes a generar

## RabbitMQ Event Configuration
rabbitmq:
  exchange:
    orders: pedidos.creados
  routing:
    key:
      order:
        created: order.created